name: Linux-GCC

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-linux-gcc:
    strategy:
      matrix:
        compiler: [ gcc:10 ]
        config: [ Debug, Release ]
    runs-on: ubuntu-22.04
    container: ${{matrix.compiler}}
    steps:
      - uses: actions/checkout@v4
      - name: Install prerequisites
        run: |
          apt update -y
          apt upgrade -y
          apt install -y cmake build-essential clang-tidy clang-tools cppcheck

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{matrix.config}} \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          -DLINQ_BUILD_TESTS=ON \
          -DLINQ_ENABLE_CPPCHECK=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.config}}

      - name: Run Tests
        run: ${{github.workspace}}/build/tests/linq_tests
