name: Linux:Clang

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-linux-clang:
    strategy:
      matrix:
        clang: [ 16 ]
        config: [ Debug, Release ]
    runs-on: ubuntu-22.04
    container: gcc:10
    steps:
      - uses: actions/checkout@v4
      - name: Install prerequisites
        run: |
          apt update -y
          apt upgrade -y
          apt install -y cmake build-essential lsb-release wget software-properties-common gnupg cppcheck

      - name: Install Clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x ./llvm.sh
          ./llvm.sh ${{matrix.clang}} all

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{matrix.config}} \
          -DCMAKE_C_COMPILER=clang-${{matrix.clang}} \
          -DCMAKE_CXX_COMPILER=clang++-${{matrix.clang}} \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          -DLINQ_BUILD_TESTS=ON \
          -DLINQ_ENABLE_CPPCHECK=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.config}}

      - name: Run Tests
        run: ${{github.workspace}}/build/tests/linq_tests
