name: CMake Build

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-linux-gcc13:
    runs-on: ubuntu-22.04
    container: gcc:13
    steps:
      - uses: actions/checkout@v4
      - name: Install prerequisites
        run: |
          apt update -y
          apt upgrade -y
          apt install -y cmake build-essential xorg-dev clang-tidy clang-tools

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          -DLINQ_BUILD_TESTS=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release

      - name: Run Tests
        run: ${{github.workspace}}/build/bin/linq_tests


  build-linux-clang16:
    runs-on: ubuntu-22.04
    container: gcc:13
    steps:
      - uses: actions/checkout@v4
      - name: Install prerequisites
        run: |
          apt update -y
          apt upgrade -y
          apt install -y cmake build-essential lsb-release wget software-properties-common gnupg

      - name: Install Clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x ./llvm.sh
          ./llvm.sh 16 all

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_COMPILER=clang-16 \
          -DCMAKE_CXX_COMPILER=clang++-16 \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          -DLINQ_BUILD_TESTS=ON \

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release

      - name: Run Tests
        run: ${{github.workspace}}/build/bin/linq_tests

  build-windows-vs2022:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build -DLINQ_BUILD_TESTS=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release

      - name: Run Tests
        run: ${{github.workspace}}\build\bin\Release\linq_tests.exe

  build-macos-13:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake (Xcode)
        run: |
          cmake -B ${{github.workspace}}/build -G Xcode -DCMAKE_BUILD_TYPE=Release -DLINQ_BUILD_TESTS=ON

      - name: Build (Xcode)
        run: cmake --build ${{github.workspace}}/build --config Release

      - name: Run Tests
        run: ${{github.workspace}}/build/bin/Release/linq_tests


  build-macos-14:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake (Xcode)
        run: |
          cmake -B ${{github.workspace}}/build -G Xcode -DCMAKE_BUILD_TYPE=Release -DLINQ_BUILD_TESTS=ON

      - name: Build (Xcode)
        run: cmake --build ${{github.workspace}}/build --config Release

      - name: Run Tests
        run: ${{github.workspace}}/build/bin/Release/linq_tests
